var page_changes_in_r15 =
[
    [ "Naming Changes", "page_changes_in_r15.html#section_changesinr15_namingchanges", null ],
    [ "API Changes", "page_changes_in_r15.html#section_changesinr15_apichanges", null ],
    [ "Important Notes", "page_changes_in_r15.html#section_changesinr15_importantnotes", null ],
    [ "Development Environments", "page_changes_in_r15.html#section_changesinr15_developmentenvironments", null ],
    [ "SDK Examples", "page_changes_in_r15.html#section_changesinr15_sdkexamples", null ],
    [ "Changes in R15.057", "page_changes_in_r15.html#section_changesinr15057", null ],
    [ "API Change List in R15", "page_api_change_list_in_r15.html", [
      [ "c4d_basebitmap.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basebitmap_h", null ],
      [ "c4d_basechannel.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basechannel_h", null ],
      [ "c4d_basecontainer.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basecontainer_h", null ],
      [ "c4d_basedocument.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basedocument_h", null ],
      [ "c4d_basedraw.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basedraw_h", null ],
      [ "c4d_baselist.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_baselist_h", null ],
      [ "c4d_basetag.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basetag_h", null ],
      [ "c4d_coffee.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_coffee_h", null ],
      [ "c4d_customdatatype.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_customdatatype_h", null ],
      [ "c4d_file.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_file_h", null ],
      [ "c4d_gedata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_gedata_h", null ],
      [ "c4d_general.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_general_h", null ],
      [ "c4d_graphview.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_graphview_h", null ],
      [ "c4d_gui.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_gui_h", null ],
      [ "c4d_library.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_library_h", null ],
      [ "c4d_memory.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_memory_h", null ],
      [ "c4d_network.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_network_h", null ],
      [ "c4d_nodedata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_nodedata_h", null ],
      [ "c4d_omp.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_omp_h", null ],
      [ "c4d_painter.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_painter_h", null ],
      [ "c4d_particles.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_particles_h", null ],
      [ "c4d_plugin.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_plugin_h", null ],
      [ "c4d_quaternion.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_quaternion_h", null ],
      [ "c4d_raytrace.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_raytrace_h", null ],
      [ "c4d_shader.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_shader_h", null ],
      [ "c4d_shaderdata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_shaderdata_h", null ],
      [ "c4d_string.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_string_h", null ],
      [ "c4d_thread.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_thread_h", null ],
      [ "c4d_tools.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_tools_h", null ],
      [ "c4d_uuid.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_uuid_h", null ],
      [ "c4d_videopostdata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_videopostdata_h", null ],
      [ "customgui_kerning.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_customgui_kerning_h", null ],
      [ "customgui_listview.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_customgui_listview_h", null ],
      [ "customgui_splinecontrol.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_customgui_splinecontrol_h", null ],
      [ "ge_autoptr.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_autoptr_h", null ],
      [ "ge_lmatrix.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_lmatrix_h", null ],
      [ "ge_lvector.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_lvector_h", null ],
      [ "ge_matrix.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_matrix_h", null ],
      [ "ge_prepass.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_prepass_h", null ],
      [ "ge_vector.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_vector_h", null ],
      [ "gui.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_gui_h", null ],
      [ "lib_batchrender.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_batchrender_h", null ],
      [ "lib_big_integer.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_big_integer_h", null ],
      [ "lib_ca.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_ca_h", null ],
      [ "lib_clipmap.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_clipmap_h", null ],
      [ "lib_description.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_description_h", null ],
      [ "lib_hair.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_hair_h", null ],
      [ "lib_iconcollection.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_iconcollection_h", null ],
      [ "lib_intersect.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_intersect_h", null ],
      [ "lib_net.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_net_h", null ],
      [ "lib_pictureviewer.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_pictureviewer_h", null ],
      [ "lib_prefs.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_prefs_h", null ],
      [ "lib_py.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_py_h", null ],
      [ "lib_sculpt.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_sculpt_h", null ],
      [ "lib_sculptbrush.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_sculptbrush_h", null ],
      [ "lib_secure_random.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_secure_random_h", null ],
      [ "matrix4.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_matrix4_h", null ],
      [ "operatingsystem.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_operatingsystem_h", null ],
      [ "vector4.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_vector4_h", null ]
    ] ],
    [ "API Change List in R15.057", "page_api_change_list_in_r15057.html", [
      [ "c4d_basematerial.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_c4d_basematerial_h", null ],
      [ "c4d_falloffdata.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_c4d_falloffdata_h", null ],
      [ "c4d_help.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_c4d_help_h", null ],
      [ "c4d_painter.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_c4d_painter_h", null ],
      [ "c4d_shader.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_c4d_shader_h", null ],
      [ "ge_prepass.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_ge_prepass_h", null ],
      [ "lib_batchrender.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_lib_batchrender_h", null ],
      [ "lib_ca.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_lib_ca_h", null ],
      [ "lib_net.h", "page_api_change_list_in_r15057.html#section_api_change_list_in_r15057_lib_net_h", null ]
    ] ]
];