var page_changes_in_sdk =
[
    [ "Changes in R19", "page_changes_in_r19.html", [
      [ "Changes in R19.008", "page_changes_in_r19.html#section_changesinr19008", [
        [ "Development Environment Requirements", "page_changes_in_r19.html#section_changesinr19008_requirements", null ],
        [ "GPU Renderer", "page_changes_in_r19.html#section_changesinr19008_gpu", null ],
        [ "LOD Object", "page_changes_in_r19.html#section_changesinr19008_lod", null ],
        [ "Polygon Reduction", "page_changes_in_r19.html#section_changesinr19008_polyredux", null ],
        [ "Character Animation", "page_changes_in_r19.html#section_changesinr19008_character", null ],
        [ "MoGraph", "page_changes_in_r19.html#section_changesinr19008_mograph", null ],
        [ "SoftSelectionTag", "page_changes_in_r19.html#section_changesinr19008_softselectoin", null ],
        [ "Neighbor", "page_changes_in_r19.html#section_changesinr19008_neighbor", null ],
        [ "Alembic", "page_changes_in_r19.html#section_changesinr19008_alembic", null ],
        [ "Modeling", "page_changes_in_r19.html#section_changesinr19008_modeling", null ],
        [ "Spherical Camera", "page_changes_in_r19.html#section_changesinr19008_spherical_cam", null ],
        [ "Custom GUI Elements", "page_changes_in_r19.html#section_changesinr19008_customgui", null ],
        [ "Delegates", "page_changes_in_r19.html#section_changesinr19008_delegates", null ],
        [ "Miscellaneous", "page_changes_in_r19.html#section_changesinr19008_miscellaneous", null ],
        [ "API Changes in R19.008", "page_changes_in_r19.html#section_changesinr19008_apichanges19008", null ]
      ] ],
      [ "Changes in R19.024", "page_changes_in_r19.html#section_changesinr19024", null ],
      [ "Changes in R19.053", "page_changes_in_r19.html#section_changesinr19053", null ],
      [ "Changes in R19.068", "page_changes_in_r19.html#section_changesinr19068", null ]
    ] ],
    [ "Changes in R18", "page_changes_in_r18.html", [
      [ "Changes in R18.011", "page_changes_in_r18.html#section_changesinr18011", [
        [ "Development Environment Requirements", "page_changes_in_r18.html#section_changesinr18011_devenvironmentrequirements", null ],
        [ "Color Swatches API", "page_changes_in_r18.html#section_changesinr18011_colorswatchesapi", null ],
        [ "VertexColorTag", "page_changes_in_r18.html#section_changesinr18011_vertexcolortag", null ],
        [ "Substances", "page_changes_in_r18.html#section_changesinr18011_substances", null ],
        [ "MoGraph", "page_changes_in_r18.html#section_changesinr18011_mograph", null ],
        [ "Modeling", "page_changes_in_r18.html#section_changesinr18011_modeling", null ],
        [ "Materials", "page_changes_in_r18.html#section_changesinr18011_materials", null ],
        [ "Animation", "page_changes_in_r18.html#section_changesinr18011_animation", null ],
        [ "InExclude", "page_changes_in_r18.html#section_changesinr18011_inexclude", null ],
        [ "GUI", "page_changes_in_r18.html#section_changesinr18011_gui", null ],
        [ "Tags", "page_changes_in_r18.html#section_changesinr18011_tags", null ],
        [ "Token System", "page_changes_in_r18.html#section_changesinr18011_tokensystem", null ],
        [ "OpenGL", "page_changes_in_r18.html#section_changesinr18011_opengl", null ],
        [ "Threading", "page_changes_in_r18.html#section_changesinr18011_threading", null ],
        [ "Miscellaneous", "page_changes_in_r18.html#section_changesinr18011_misc", null ],
        [ "API Changes in R18.011", "page_changes_in_r18.html#section_changesinr18011_apichanges18011", null ]
      ] ],
      [ "Changes in R18.020", "page_changes_in_r18.html#section_changesinr18020", [
        [ "Motion Tracker API", "page_changes_in_r18.html#section_changesinr18020_motiontrack", null ],
        [ "Voronoi Fracture Object", "page_changes_in_r18.html#section_changesinr18020_voronoifracture", null ],
        [ "API Changes in R18.020", "page_changes_in_r18.html#section_changesinr18020_apichanges18020", null ]
      ] ],
      [ "Changes in R18.039", "page_changes_in_r18.html#section_changesinr18039", null ],
      [ "Changes in R18.057", "page_changes_in_r18.html#section_changesinr18057", null ]
    ] ],
    [ "Changes in R17", "page_changes_in_r17.html", [
      [ "Changes in R17.032", "page_changes_in_r17.html#section_changesinr17032", [
        [ "Removed Legacy Defines", "page_changes_in_r17.html#section_changesinr17032_legacydefines", null ],
        [ "Development Environment Requirements", "page_changes_in_r17.html#section_changesinr17032_devenvrequirements", null ],
        [ "Take System Support", "page_changes_in_r17.html#section_changesinr17032_takesystemsupport", null ],
        [ "Token System Support", "page_changes_in_r17.html#section_changesinr17032_tokensystemsupport", null ],
        [ "UTF-32 Unicode Strings", "page_changes_in_r17.html#section_changesinr17032_unicodestring", null ],
        [ "Sculpting Additions", "page_changes_in_r17.html#section_changesinr17032_sculptingadditions", null ],
        [ "Miscellaneous", "page_changes_in_r17.html#section_changesinr17032_miscellaneous", null ],
        [ "GitHub Repository", "page_changes_in_r17.html#section_changesinr17032_github", null ],
        [ "API Changes in R17.032", "page_changes_in_r17.html#section_changesinr17032_apichanges17032", null ]
      ] ],
      [ "Changes in R17.048", "page_changes_in_r17.html#section_changesinr17048", [
        [ "API Changes in R17.048", "page_changes_in_r17.html#section_changesinr17048_apichanges17048", null ]
      ] ],
      [ "Changes in R17.053", "page_changes_in_r17.html#section_changesinr17053", [
        [ "API Changes in R17.053", "page_changes_in_r17.html#section_changesinr17053_apichanges17053", null ]
      ] ]
    ] ],
    [ "Changes in R16", "page_changes_in_r16.html", "page_changes_in_r16" ],
    [ "Changes in R15", "page_changes_in_r15.html", "page_changes_in_r15" ],
    [ "API Change List in R19", "page_api_change_list_in_r19.html", [
      [ "API Changes in R19.008", "page_api_change_list_in_r19.html#section_apichangesinr19008", [
        [ "c4d_basebitmap.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_basebitmap", null ],
        [ "c4d_basechannel.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_basechannel", null ],
        [ "c4d_basedraw.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_basedraw", null ],
        [ "c4d_baselist.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_baselist", null ],
        [ "c4d_baseobject.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_baseobject", null ],
        [ "c4d_baseplugin.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_baseplugin", null ],
        [ "c4d_basetag.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_basetag", null ],
        [ "c4d_colors.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_colors", null ],
        [ "c4d_filterdata.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_filterdata", null ],
        [ "c4d_general.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_general", null ],
        [ "c4d_gl.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_gl", null ],
        [ "c4d_gui.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_gui", null ],
        [ "c4d_painter.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_painter", null ],
        [ "c4d_plugin.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_plugin", null ],
        [ "c4d_raytrace.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_raytrace", null ],
        [ "c4d_reflection.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_reflection", null ],
        [ "c4d_shader.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_shader", null ],
        [ "c4d_spc.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_spc", null ],
        [ "c4d_videopostdata.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_c4d_videopostdata", null ],
        [ "ge_dynamicarray.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_ge_dynamicarray", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_ge_prepass", null ],
        [ "ge_sys_math.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_ge_sys_math", null ],
        [ "operatingsystem.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_operatingsystem", null ],
        [ "customgui_bitmapbool.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_customgui_bitmapbool", null ],
        [ "customgui_gradient.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_customgui_gradient", null ],
        [ "customgui_itemtree.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_customgui_itemtree", null ],
        [ "customgui_quicktab.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_customgui_quicktab", null ],
        [ "customgui_range.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_customgui_range", null ],
        [ "customgui_soundeffector.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_customgui_soundeffector", null ],
        [ "lib_ca.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_lib_ca", null ],
        [ "lib_description.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_lib_description", null ],
        [ "lib_lodobject.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_lib_lodobject", null ],
        [ "lib_net.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_lib_net", null ],
        [ "lib_polygonreduction.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_lib_polygonreduction", null ],
        [ "lib_substance.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_lib_substance", null ],
        [ "lib_voronoifracture.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_lib_voronoifracture", null ],
        [ "delegate.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_maxon_delegate", null ],
        [ "general.h", "page_api_change_list_in_r19.html#section_apichangesinr19008_maxon_general", null ]
      ] ],
      [ "API Changes in R19.024", "page_api_change_list_in_r19.html#section_apichangesinr19024", [
        [ "c4d_baselist.h", "page_api_change_list_in_r19.html#section_apichangesinr19024_c4d_baselist", null ],
        [ "c4d_baseobject.h", "page_api_change_list_in_r19.html#section_apichangesinr19024_c4d_baseobject", null ],
        [ "c4d_falloffdata.h", "page_api_change_list_in_r19.html#section_apichangesinr19024_c4d_falloffdata", null ],
        [ "c4d_gl.h", "page_api_change_list_in_r19.html#section_apichangesinr19024_c4d_gl", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r19.html#section_apichangesinr19024_ge_prepass", null ],
        [ "customgui_soundeffector.h", "page_api_change_list_in_r19.html#section_apichangesinr19024_customgui_soundeffector", null ]
      ] ],
      [ "API Changes in R19.053", "page_api_change_list_in_r19.html#section_apichangesinr19053", [
        [ "c4d_basedraw.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_c4d_basedraw", null ],
        [ "c4d_baseeffectordata.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_c4d_baseeffector", null ],
        [ "c4d_falloffdata.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_c4d_falloffdata", null ],
        [ "c4d_shader.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_c4d_shader", null ],
        [ "c4d_tooldata.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_customgui_c4d_tooldata", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_customgui_ge_prepass", null ],
        [ "customgui_bitmapbool.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_customgui_bitmapbool", null ],
        [ "customgui_soundeffector.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_customgui_soundeffector", null ],
        [ "lib_ca.h", "page_api_change_list_in_r19.html#section_apichangesinr19053_lib_ca", null ]
      ] ],
      [ "API Changes in R19.068", "page_api_change_list_in_r19.html#section_apichangesinr19068", [
        [ "c4d_baselist.h", "page_api_change_list_in_r19.html#section_apichangesinr19068_c4d_baselist", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r19.html#section_apichangesinr19068_ge_prepass", null ]
      ] ]
    ] ],
    [ "API Change List in R18", "page_api_change_list_in_r18.html", [
      [ "API Changes in R18.011", "page_api_change_list_in_r18.html#section_apichangesinr18011", [
        [ "c4d_basedraw.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_basedraw_h", null ],
        [ "c4d_baseeffectordata.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_baseeffectordata_h", null ],
        [ "c4d_baselist.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_baselist_h", null ],
        [ "c4d_basematerial.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_basematerial_h", null ],
        [ "c4d_baseobject.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_baseobject_h", null ],
        [ "c4d_basetag.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_basetag_h", null ],
        [ "c4d_canimation.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_canimation_h", null ],
        [ "c4d_falloffdata.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_falloffdata_h", null ],
        [ "c4d_general.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_general_h", null ],
        [ "c4d_gui.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_gui_h", null ],
        [ "c4d_quaternion.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_quaternion_h", null ],
        [ "c4d_raytrace.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_raytrace_h", null ],
        [ "c4d_reflection.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_reflection_h", null ],
        [ "c4d_snapdata.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_snapdata_h", null ],
        [ "c4d_tooldata.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_tooldata_h", null ],
        [ "ge_lmatrix.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_lmatrix_h", null ],
        [ "c4d_tools.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_tools_h", null ],
        [ "operatingsystem.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_operatingsystem_h", null ],
        [ "ge_math.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_math_h", null ],
        [ "ge_matrix.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_matrix_h", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_prepass_h", null ],
        [ "gui.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_gui_h", null ],
        [ "modelingids.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_modelingids_h", null ],
        [ "customgui_inexclude.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_customgui_inexclude_h", null ],
        [ "customgui_listview.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_customgui_listview_h", null ],
        [ "c4d_graphview_def.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_graphview_def_h", null ],
        [ "lib_aes.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_lib_aes_h", null ],
        [ "lib_description.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_lib_description_h", null ],
        [ "lib_colorchooser.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_lib_colorchoose_h", null ],
        [ "lib_net.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_lib_net_h", null ],
        [ "lib_substance.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_lib_substance_h", null ],
        [ "lib_token.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_lib_token_h", null ],
        [ "general.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_misc_general_h", null ],
        [ "apibasemath.h", "page_api_change_list_in_r18.html#section_apichangesinr18011_c4d_misc_utilities_apibasemath_h", null ]
      ] ],
      [ "API Changes in R18.020", "page_api_change_list_in_r18.html#section_apichangesinr18020", [
        [ "c4d_baseobject.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_c4d_baseobject_h", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_ge_prepass_h", null ],
        [ "customgui_inexclude.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_customgui_inexclude_h", null ],
        [ "lib_birender.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_lib_birender_h", null ],
        [ "lib_motiontracker.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_lib_motiontracker_h", null ],
        [ "lib_net.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_lib_net_h", null ],
        [ "lib_substance.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_lib_substance_h", null ],
        [ "lib_voronoifracture.h", "page_api_change_list_in_r18.html#section_apichangesinr18020_lib_voronoifracture_h", null ]
      ] ],
      [ "API Changes in R18.039", "page_api_change_list_in_r18.html#section_apichangesinr18039", [
        [ "c4d_baselist.h", "page_api_change_list_in_r18.html#section_apichangesinr18039_lib_c4d_baselist_h", null ],
        [ "c4d_animation.h", "page_api_change_list_in_r18.html#section_apichangesinr18039_lib_c4d_animation_h", null ],
        [ "c4d_materialdata.h", "page_api_change_list_in_r18.html#section_apichangesinr18039_c4d_materialdata_h", null ],
        [ "c4d_raytrace.h", "page_api_change_list_in_r18.html#section_apichangesinr18039_c4d_raytrace_h", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r18.html#section_apichangesinr18039_lib_ge_prepass_h", null ],
        [ "lib_snd.h", "page_api_change_list_in_r18.html#section_apichangesinr18039_lib_snd_h", null ]
      ] ],
      [ "API Changes in R18.057", "page_api_change_list_in_r18.html#section_apichangesinr18057", [
        [ "c4d_reflection.h", "page_api_change_list_in_r18.html#section_apichangesinr18057_c4d_reflection", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r18.html#section_apichangesinr18057_ge_prepass_h", null ],
        [ "gui.h", "page_api_change_list_in_r18.html#section_apichangesinr18057_gui_h", null ],
        [ "modelingids.h", "page_api_change_list_in_r18.html#section_apichangesinr18057_modelingids_h", null ],
        [ "customgui_kerning.h", "page_api_change_list_in_r18.html#section_apichangesinr18057_customgui_kerning_h", null ],
        [ "customgui_longlat.h", "page_api_change_list_in_r18.html#section_apichangesinr18057_customgui_longlat_h", null ]
      ] ]
    ] ],
    [ "API Change List in R17", "page_api_change_list_in_r17.html", [
      [ "API Changes in R17.032", "page_api_change_list_in_r17.html#section_apichangesinr17032", [
        [ "c4d_basecontainer.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_basecontainer_h", null ],
        [ "c4d_basedocument.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_basedocument_h", null ],
        [ "c4d_baselist.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_baselist_h", null ],
        [ "c4d_baseselect.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_baseselect_h", null ],
        [ "c4d_basetag.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_basetag_h", null ],
        [ "c4d_canimation.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_canimation_h", null ],
        [ "c4d_colors.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_colors_h", null ],
        [ "c4d_customdatatype.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_customdatatype_h", null ],
        [ "c4d_customguidata.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_customguidata_h", null ],
        [ "c4d_general.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_general_h", null ],
        [ "c4d_gui.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_gui_h", null ],
        [ "c4d_materialdata.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_materialdata_h", null ],
        [ "c4d_messagedata.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_messagedata_h", null ],
        [ "c4d_nodedata.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_nodedata_h", null ],
        [ "c4d_painter.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_painter_h", null ],
        [ "c4d_plugin.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_plugin_h", null ],
        [ "c4d_raytrace.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_raytrace_h", null ],
        [ "c4d_reflection.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_reflection_h", null ],
        [ "c4d_shader.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_shader_h", null ],
        [ "c4d_string.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_string_h", null ],
        [ "c4d_thread.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_thread_h", null ],
        [ "c4d_tooldata.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_tooldata_h", null ],
        [ "c4d_tools.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_tools_h", null ],
        [ "c4d_videopostdata.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_videopostdata_h", null ],
        [ "ge_autoptr.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_ge_autoptr_h", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_ge_prepass_h", null ],
        [ "ge_sys_math.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_ge_sys_math_h", null ],
        [ "gui.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_gui_h", null ],
        [ "legacy.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_legacy_h", null ],
        [ "customgui_descproperty.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_customgui_descproperty_h", null ],
        [ "customgui_description.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_customgui_description_h", null ],
        [ "customgui_listview.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_customgui_listview_h", null ],
        [ "customgui_matpreview.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_customgui_matpreview_h", null ],
        [ "c4d_graphview.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_gv_c4d_graphview_h", null ],
        [ "c4d_graphview_def.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_gv_c4d_graphview_def_h", null ],
        [ "lib_activeobjectmanager.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_activeobjectmanager_h", null ],
        [ "lib_description.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_description_h", null ],
        [ "lib_hair.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_hair_h", null ],
        [ "lib_net.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_net_h", null ],
        [ "lib_sculpt.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_sculpt_h", null ],
        [ "lib_sculptbrush.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_sculptbrush_h", null ],
        [ "lib_splinehelp.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_splinehelp_h", null ],
        [ "lib_takesystem.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_takesystem_h", null ],
        [ "lib_token.h", "page_api_change_list_in_r17.html#section_apichangesinr17032_c4d_libs_lib_token_h", null ]
      ] ],
      [ "API Changes in R17.048", "page_api_change_list_in_r17.html#section_apichangesinr17048", [
        [ "c4d_gedata.h", "page_api_change_list_in_r17.html#section_apichangesinr17048_c4d_gedata_h", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r17.html#section_apichangesinr17048_ge_prepass_h", null ],
        [ "gui.h", "page_api_change_list_in_r17.html#section_apichangesinr17048_gui_h", null ],
        [ "customgui_filename.h", "page_api_change_list_in_r17.html#section_apichangesinr17048_c4d_customgui_filename_h", null ],
        [ "lib_ca.h", "page_api_change_list_in_r17.html#section_apichangesinr17048_c4d_libs_lib_ca_h", null ]
      ] ],
      [ "API Changes in R17.053", "page_api_change_list_in_r17.html#section_apichangesinr17053", [
        [ "ge_prepass.h", "page_api_change_list_in_r17.html#section_apichangesinr17053_ge_prepass_h", null ],
        [ "gui.h", "page_api_change_list_in_r17.html#section_apichangesinr17053_gui_h", null ],
        [ "lib_net.h", "page_api_change_list_in_r17.html#section_apichangesinr17053_lib_net_h", null ],
        [ "hashmap.h", "page_api_change_list_in_r17.html#section_apichangesinr17053_hashmap_h", null ]
      ] ]
    ] ],
    [ "API Change List in R16", "page_api_change_list_in_r16.html", [
      [ "API Changes in R16.021", "page_api_change_list_in_r16.html#section_apichangesinr16021", [
        [ "c4d_basedocument.h", "page_api_change_list_in_r16.html#section_c4d_basedocument_h", null ],
        [ "c4d_basematerial.h", "page_api_change_list_in_r16.html#section_c4d_basematerial_h", null ],
        [ "c4d_file.h", "page_api_change_list_in_r16.html#section_c4d_file_h", null ],
        [ "c4d_network.h", "page_api_change_list_in_r16.html#section_c4d_network_h", null ],
        [ "c4d_painter.h", "page_api_change_list_in_r16.html#section_c4d_painter_h", null ],
        [ "c4d_raytrace.h", "page_api_change_list_in_r16.html#section_c4d_raytrace_h", null ],
        [ "c4d_shader.h", "page_api_change_list_in_r16.html#section_c4d_shader_h", null ],
        [ "c4d_snapdata.h", "page_api_change_list_in_r16.html#section_c4d_snapdata_h", null ],
        [ "c4d_tools.h", "page_api_change_list_in_r16.html#section_c4d_tools_h", null ],
        [ "c4d_videopostdata.h", "page_api_change_list_in_r16.html#section_c4d_videopostdata_h", null ]
      ] ],
      [ "API Changes in R16.038", "page_api_change_list_in_r16.html#section_apichangesinr16038", [
        [ "c4d_baselist.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_c4d_baselist_h", null ],
        [ "c4d_general.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_c4d_general_h", null ],
        [ "c4d_shader.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_c4d_shader_h", null ],
        [ "c4d_tools.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_c4d_tools_h", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_ge_prepass_h", null ],
        [ "c4d_particles.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_c4d_gv_c4d_particles_h", null ],
        [ "hp_particledata.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_description_hp_particledata_h", null ],
        [ "op_particledata.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_description_op_particledata_h", null ],
        [ "Tfbxexportreference.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_description_tfbxexportreference_h", null ],
        [ "tp_group.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_description_tp_group_h", null ],
        [ "vpxmbsampler.h", "page_api_change_list_in_r16.html#section_apichangesinr16038_description_vpxmbsampler_h", null ]
      ] ],
      [ "API Changes in R16.050", "page_api_change_list_in_r16.html#section_apichangesinr16050", [
        [ "c4d_baselist.h", "page_api_change_list_in_r16.html#section_apichangesinr16050_c4d_baselist_h", null ],
        [ "c4d_baseobject.h", "page_api_change_list_in_r16.html#section_apichangesinr16050_c4d_baseobject_h", null ],
        [ "ge_prepass.h", "page_api_change_list_in_r16.html#section_apichangesinr16050_ge_prepass_h", null ],
        [ "c4d_graphview.h", "page_api_change_list_in_r16.html#section_apichangesinr16050_c4d_gv_c4d_graphview_h", null ],
        [ "c4d_particles.h", "page_api_change_list_in_r16.html#section_apichangesinr16050_c4d_gv_c4d_particles_h", null ]
      ] ]
    ] ],
    [ "API Change List in R15", "page_api_change_list_in_r15.html", [
      [ "c4d_basebitmap.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basebitmap_h", null ],
      [ "c4d_basechannel.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basechannel_h", null ],
      [ "c4d_basecontainer.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basecontainer_h", null ],
      [ "c4d_basedocument.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basedocument_h", null ],
      [ "c4d_basedraw.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basedraw_h", null ],
      [ "c4d_baselist.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_baselist_h", null ],
      [ "c4d_basetag.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_basetag_h", null ],
      [ "c4d_coffee.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_coffee_h", null ],
      [ "c4d_customdatatype.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_customdatatype_h", null ],
      [ "c4d_file.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_file_h", null ],
      [ "c4d_gedata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_gedata_h", null ],
      [ "c4d_general.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_general_h", null ],
      [ "c4d_graphview.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_graphview_h", null ],
      [ "c4d_gui.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_gui_h", null ],
      [ "c4d_library.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_library_h", null ],
      [ "c4d_memory.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_memory_h", null ],
      [ "c4d_network.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_network_h", null ],
      [ "c4d_nodedata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_nodedata_h", null ],
      [ "c4d_omp.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_omp_h", null ],
      [ "c4d_painter.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_painter_h", null ],
      [ "c4d_particles.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_particles_h", null ],
      [ "c4d_plugin.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_plugin_h", null ],
      [ "c4d_quaternion.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_quaternion_h", null ],
      [ "c4d_raytrace.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_raytrace_h", null ],
      [ "c4d_shader.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_shader_h", null ],
      [ "c4d_shaderdata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_shaderdata_h", null ],
      [ "c4d_string.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_string_h", null ],
      [ "c4d_thread.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_thread_h", null ],
      [ "c4d_tools.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_tools_h", null ],
      [ "c4d_uuid.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_uuid_h", null ],
      [ "c4d_videopostdata.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_c4d_videopostdata_h", null ],
      [ "customgui_kerning.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_customgui_kerning_h", null ],
      [ "customgui_listview.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_customgui_listview_h", null ],
      [ "customgui_splinecontrol.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_customgui_splinecontrol_h", null ],
      [ "ge_autoptr.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_autoptr_h", null ],
      [ "ge_lmatrix.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_lmatrix_h", null ],
      [ "ge_lvector.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_lvector_h", null ],
      [ "ge_matrix.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_matrix_h", null ],
      [ "ge_prepass.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_prepass_h", null ],
      [ "ge_vector.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_ge_vector_h", null ],
      [ "gui.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_gui_h", null ],
      [ "lib_batchrender.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_batchrender_h", null ],
      [ "lib_big_integer.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_big_integer_h", null ],
      [ "lib_ca.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_ca_h", null ],
      [ "lib_clipmap.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_clipmap_h", null ],
      [ "lib_description.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_description_h", null ],
      [ "lib_hair.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_hair_h", null ],
      [ "lib_iconcollection.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_iconcollection_h", null ],
      [ "lib_intersect.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_intersect_h", null ],
      [ "lib_net.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_net_h", null ],
      [ "lib_pictureviewer.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_pictureviewer_h", null ],
      [ "lib_prefs.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_prefs_h", null ],
      [ "lib_py.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_py_h", null ],
      [ "lib_sculpt.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_sculpt_h", null ],
      [ "lib_sculptbrush.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_sculptbrush_h", null ],
      [ "lib_secure_random.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_lib_secure_random_h", null ],
      [ "matrix4.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_matrix4_h", null ],
      [ "operatingsystem.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_operatingsystem_h", null ],
      [ "vector4.h", "page_api_change_list_in_r15.html#section_api_change_list_in_r15_vector4_h", null ]
    ] ],
    [ "Transition to Cinema 4D R15 API", "page_transition_to_r15_api.html", "page_transition_to_r15_api" ]
];